backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true
  commit_messages:
    create: 'cms: create {{collection}} “{{slug}}” by "{{author-name}}"'
    update: 'cms: update {{collection}} “{{slug}} by "{{author-name}}"”'
    delete: 'cms: delete {{collection}} “{{slug}} by {{author-name}}”'
    uploadMedia: 'cms: upload “{{path}}” by {{author-name}}'
    deleteMedia: 'cms: delete “{{path}} by {{author-name}}”'
    openAuthoring: '{{message}}'

publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Tutorial" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: '/tutorial/{{slug}}?open_thumbnail=true'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - label: "Topik"
        name: "tags"
        widget: "relation"
        collection: "tags"
        value_field: "{{slug}}"
        search_fields: ["name"]
        display_fields: ["name"]
        multiple: true
      - label: "Related Tutorial"
        name: "related"
        widget: "relation"
        collection: "blog"
        value_field: "{{slug}}"
        search_fields: ["title"]
        display_fields: ["title"]
        multiple: true
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tags"
    label: "Topik"
    folder: "src/content/tags"
    create: true
    slug: "{{name}}"
    preview_path: '/tags/{{name}}?open_thumbnail=true'
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
